[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gpibtool"
version = "1!0.0.1787193092"
description = "Common functions for GPIB control"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
license = "ISC"
dependencies = [
    "click",
    "pyserial",
    "pyvisa",
    "sh",
    "asserttool @ git+https://github.com/jakeogh/asserttool@4bd23a06c2161e488415acde89c29537e6720cc1",
    "bnftool @ git+https://github.com/jakeogh/bnftool@ad5c7cdd80c1c8ff20480a3eff1e0ed0c3abebbc",
    "click-auto-help @ git+https://github.com/jakeogh/click-auto-help@c53f57c78529a51ae9b03f579d7ee6f2d63ca03a",
    "clicktool @ git+https://github.com/jakeogh/clicktool@a9894f9d3a06701c5f73cd8b2794028042c9b420",
    "eprint @ git+https://github.com/jakeogh/eprint@6ee1deca0c24b684eb5093247d6bd22e11f1b057",
    "globalverbose @ git+https://github.com/jakeogh/globalverbose@59abc758c18c0b85e9e61c1e14e5a64a81bb220e",
    "mptool @ git+https://github.com/jakeogh/mptool@a8579325a458cc33c6a212685aa50e16a457ccf6",
    "stdiotool @ git+https://github.com/jakeogh/stdiotool@e22dbff405625082bf2f84198f73879190119c79",
]
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/jakeogh/gpibtool"

[project.scripts]
gpibtool = "gpibtool.gpibtool:cli"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
gpibtool = [
    "py.typed",
]
