[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gpibtool"
version = "1!0.0.1789730264"
description = "Common functions for GPIB control"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
license = "ISC"
dependencies = [
    "click",
    "pyserial",
    "pyvisa",
    "sh",
    "asserttool @ git+https://github.com/jakeogh/asserttool@4bd23a06c2161e488415acde89c29537e6720cc1",
    "bnftool @ git+https://github.com/jakeogh/bnftool@ad5c7cdd80c1c8ff20480a3eff1e0ed0c3abebbc",
    "click-auto-help @ git+https://github.com/jakeogh/click-auto-help@0308bf2e30095ce9c87a083e1f013731827e60aa",
    "clicktool @ git+https://github.com/jakeogh/clicktool@4bc98af7590652693aef664af7485acde40688c2",
    "eprint @ git+https://github.com/jakeogh/eprint@6ee1deca0c24b684eb5093247d6bd22e11f1b057",
    "globalverbose @ git+https://github.com/jakeogh/globalverbose@ed36633a3208520a523e528e9371988fc33ffea3",
    "mptool @ git+https://github.com/jakeogh/mptool@49db67178bc07c5664b20d9d0313746af08b039c",
    "stdiotool @ git+https://github.com/jakeogh/stdiotool@e22dbff405625082bf2f84198f73879190119c79",
]
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/jakeogh/gpibtool"

[project.scripts]
gpibtool = "gpibtool.gpibtool:cli"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.package-data]
gpibtool = [
    "py.typed",
]
